# Site settings
title: wzdark's Blog
email: wzfindjob@163.com
description: "JAVA,Javascript,HTML,CSS"
permalink: /:year/:month/:day/:title.html
baseurl: "/personalInfo"
url: "http://hackerxu.com"
atom-baseurl: "http://hackerxu.com"
author: "wzdark"

# Build settings
# permalink: date

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : taizilongxu

navigations:
  - title: About
    class: fa fa-list-ul
    href: /about/
  - title: Archive
    class: fa fa-tags
    href: /archive/
  - title: Categories
    class: fa fa-user
    href: /categories/
  - title: Tags
    class: fa fa-film
    href: /tags/
  - title: Rss
    class: fa fa-rss
    href: /atom.xml
